-- FHIR Condition Resource DDL
CREATE OR REPLACE TABLE FHIR_CONDITION_RESOURCE_STG (
    ID VARCHAR(16777216) COLLATE 'utf8',
    CLINICAL_STATUS VARIANT,
    VERIFICATION_STATUS VARIANT,
    CATEGORY ARRAY,
    SEVERITY VARIANT,
    CODE VARIANT,
    BODY_SITE ARRAY,
    SUBJECT VARIANT,
    ENCOUNTER VARIANT,
    ONSET VARIANT,
    ABATEMENT VARIANT,
    RECORDED_DATE VARCHAR(16777216) COLLATE 'utf8',
    RECORDER VARIANT,
    ASSERTER VARIANT,
    STAGE ARRAY,
    EVIDENCE ARRAY,
    NOTE ARRAY,
    META VARIANT,
    IDENTIFIER ARRAY
);
