-- FHIR Location Resource DDL
CREATE OR REPLACE TABLE FHIR_LOCATION_RESOURCE_STG (
    ID VARCHAR(16777216) COLLATE 'utf8',
    STATUS VARCHAR(16777216) COLLATE 'utf8',
    NAME VARCHAR(16777216) COLLATE 'utf8',
    ALIAS ARRAY,
    DESCRIPTION VARCHAR(16777216) COLLATE 'utf8',
    MODE VARCHAR(16777216) COLLATE 'utf8',
    TYPE ARRAY,
    TELECOM ARRAY,
    ADDRESS VARIANT,
    PHYSICAL_TYPE VARIANT,
    POSITION VARIANT,
    MANAGING_ORGANIZATION VARIANT,
    PART_OF VARIANT,
    META VARIANT,
    IDENTIFIER ARRAY
);
