-- FHIR Organization Resource DDL
CREATE OR REPLACE TABLE FHIR_ORGANIZATION_RESOURCE_STG (
    ID VARCHAR(16777216) COLLATE 'utf8',
    ACTIVE VARCHAR(16777216) COLLATE 'utf8',
    TYPE ARRAY,
    NAME VARCHAR(16777216) COLLATE 'utf8',
    ALIAS ARRAY,
    TELECOM ARRAY,
    ADDRESS ARRAY,
    PART_OF VARIANT,
    CONTACT ARRAY,
    ENDPOINT ARRAY,
    META VARIANT,
    IDENTIFIER ARRAY
);
