-- FHIR Practitioner Resource DDL
CREATE OR REPLACE TABLE FHIR_PRACTITIONER_RESOURCE_STG (
    ID VARCHAR(16777216) COLLATE 'utf8',
    ACTIVE VARCHAR(16777216) COLLATE 'utf8',
    NAME ARRAY,
    TELECOM ARRAY,
    ADDRESS ARRAY,
    GENDER VARCHAR(16777216) COLLATE 'utf8',
    BIRTHDATE VARCHAR(16777216) COLLATE 'utf8',
    PHOTO ARRAY,
    QUALIFICATION ARRAY,
    COMMUNICATION ARRAY,
    META VARIANT,
    IDENTIFIER ARRAY
);
